export const dictionary = {
  en: {
    welcome: "Welcome to",
    continue: "Continue",
    language: "Chose your desired language",
    choose: "Choose",
    whyKrishika: "Why Krishika?",
    why1: `Simplifying the process of selling your farm produces with ease.`,
    why2: "An efficient solution to the land fragmentation problem in our country",
    why3: "A well maintained community forum guided by agricultural experts, to address every doubt or problem that you face while farming.",
    why4: "A social media forum just for our farmer friends.",
    why5: "And all of this above to ensure that our farmer friends get the price closest to MSP*, while selling their goods.",
    joinUs1: "Come with us,  Let’s give our farmer friends the",
    joinUs2: " support and dignity",
    jonUs3: "they deserve.",
    joinUs: "Join Us",
    FAQ: "Basic things every farmer should know.",
    MSP: "What is MSP?",
    MSPANSWER:
      "Minimum Support Price or MSP is an Agriculture product price set by the Government of India to purchase directly from the farmer. This price is to safeguard farmer to minimum profit for the harvest, if the open market has lesser price than the cost incurred.",
    readMore: "Read More",
    logIn: "Log In",
    loginTop: "Welcome back, let’s start another fresh day.",
    mobileNumber: "Mobile Number",
    loginContinue:
      "On continuing you will get an OTP, on your registered phone number",
    notRegistered: "Not registered ?",
    signUp: " Sign up",
    signUpTop: "Let’s start an amazing journey together",
    fullName: "Full Name",
    address: "Address",
    zipCode: "Zip Code",
    district: "District",
    iama: "I am a(an)",
    landSize: "Land Size (N/A if you don't have)",
    email: "Email",
    alreadyRegistered: "Already registered?",
    OTP: "OTP verification",
    otpTop: "Enter your OTP to begin.",
    otpHere: "Enter OTP here",
    resendOTP: "Didn't recieve? resend",
    preferredLanguage: "Preferred Langauge",
    otpSent: "OTP has been sent to your mobile number",
    formNotFilled: "Please fill up all fields",
    mobInvalid: "Please Enter a valid mobile number",
    wrongOTP: "You have entered a wrong OTP",
    home: "Home",
    feed: "Feed",
    forum: "Forum",
    mandi: "Mandi",
    actions: "Actions",
    profile: "Profile",
    logout: "Log out",
    dashboard: "Dashboard",
    searchDistrict: "Search District",
  },
  bn: {
    welcome: "স্বাগতম",
    continue: "এগিয়ে চলো",
    language: "আপনার পছন্দসই ভাষা চয়ন করুন",
    choose: "চয়ন করুন",
    whyKrishika: "কৃষিকা কেন?",
    why1: "আপনার খামারের উত্পাদন গুলি সহজেই বিক্রি করার প্রক্রিয়াটি সহজ করা",
    why2: "আমাদের দেশে ভূমি বিভাজন সমস্যার একটি কার্যকর সমাধান",
    why3: "কৃষি বিশেষজ্ঞদের দ্বারা পরিচালিত একটি ভাল রক্ষণাবেক্ষণ কমিউনিটি ফোরাম, যা চাষের সময় আপনার মুখোমুখি হওয়া প্রতিটি সন্দেহ বা সমস্যার সমাধান করে।",
    why4: "আমাদের কৃষক বন্ধুদের জন্য একটি সোশ্যাল মিডিয়া ফোরাম।",
    why5: "এবং উপরের এই সমস্ত কিছু নিশ্চিত করার জন্য যে আমাদের কৃষক বন্ধুরা তাদের পণ্য বিক্রি করার সময় এমএসপি * এর নিকটতম দাম পান।",
    joinUs1: "আসুন আমাদের সাথে আসুন, আমাদের ",
    joinUs2: "কৃষক বন্ধুদের তাদের প্রাপ্য সমর্থন এবং মর্যাদা",
    jonUs3: " দিন",
    joinUs: "যোগ দিন",
    FAQ: "মৌলিক বিষয়গুলো প্রত্যেক কৃষকের জানা উচিত।",
    MSP: "এমএসপি কি?",
    MSPANSWER:
      "ন্যূনতম সহায়ক মূল্য বা এমএসপি হ'ল ভারত সরকার কর্তৃক কৃষকের কাছ থেকে সরাসরি ক্রয়ের জন্য নির্ধারিত একটি কৃষি পণ্যের মূল্য। এই মূল্যটি কৃষককে ফসলের জন্য ন্যূনতম মুনাফা থেকে রক্ষা করার জন্য, যদি খোলা বাজারে ব্যয়ের চেয়ে কম দাম থাকে।",
    readMore: "আরও পড়ুন",
    logIn: "লগইন",
    loginTop: "স্বাগতম, আসুন আরেকটি নতুন দিন শুরু করি।",

    mobileNumber: "মোবাইল নম্বর",
    loginContinue: "আপনি আপনার নিবন্ধিত ফোন নম্বরে একটি ওটিপি পাবেন",
    notRegistered: "নিবন্ধিত নয় ?",
    signUp: " সাইন আপ করো ",
    signUpTop: "আসুন একসাথে একটি সুন্দর যাত্রা শুরু করি",
    fullName: "পুরো নাম",
    address: "ঠিকানা",
    zipCode: "জিপ কোড",
    district: "জেলা",
    iama: "আমি একজন",
    landSize: "জমির আকার (আপনার যদি না থাকে তবে এন / এ)",
    email: "ইমেল",
    alreadyRegistered: "ইতিমধ্যে নিবন্ধিত?",
    OTP: "OTP যাচাইকরণ",
    otpTop: "শুরু করতে আপনার OTP লিখুন।",
    otpHere: "এখানে OTP লিখুন",
    resendOTP: "গ্রহণ করেননি? পুনরায় প্রেরণ",
    preferredLanguage: "পছন্দসই Langauge",
    otpSent: "আপনার মোবাইল নম্বরে OTP পাঠানো হয়েছে",
    formNotFilled: "দয়া করে সমস্ত ক্ষেত্র পূরণ করুন",
    mobInvalid: "অনুগ্রহ করে একটি বৈধ মোবাইল নম্বর লিখুন",
    wrongOTP: "আপনি একটি ভুল OTP প্রবেশ করেছেন",
    home: "বাড়ি",
    feed: "বার্তা",
    forum: "ফোরাম",
    mandi: "মন্ডি",
    actions: "মেনু",
    profile: "প্রোফাইল",
    logout: "প্রস্থান",
    dashboard: "ড্যাশবোর্ড",
    searchDistrict: "জেলা অনুসন্ধান",
  },
};
